// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiL4O_v9n9w1UiA1lMOgAUpolm_YnCR-8',
    appId: '1:609809404513:web:416e9e42bd3d6072419020',
    messagingSenderId: '609809404513',
    projectId: 'login-fir',
    authDomain: 'login-fir.firebaseapp.com',
    storageBucket: 'login-fir.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKhpcsFVE63bCCG-d2ZQM1YGVt6qzCVk',
    appId: '1:609809404513:android:e9d0006cc3fe9d20419020',
    messagingSenderId: '609809404513',
    projectId: 'login-fir',
    storageBucket: 'login-fir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlU3I5W94JPjr4SPi2Li-7oxyNyZaprVE',
    appId: '1:609809404513:ios:4c3f8b0878e8d6fe419020',
    messagingSenderId: '609809404513',
    projectId: 'login-fir',
    storageBucket: 'login-fir.appspot.com',
    iosBundleId: 'com.example.loginExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlU3I5W94JPjr4SPi2Li-7oxyNyZaprVE',
    appId: '1:609809404513:ios:4c3f8b0878e8d6fe419020',
    messagingSenderId: '609809404513',
    projectId: 'login-fir',
    storageBucket: 'login-fir.appspot.com',
    iosBundleId: 'com.example.loginExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiL4O_v9n9w1UiA1lMOgAUpolm_YnCR-8',
    appId: '1:609809404513:web:9e712239b29884b4419020',
    messagingSenderId: '609809404513',
    projectId: 'login-fir',
    authDomain: 'login-fir.firebaseapp.com',
    storageBucket: 'login-fir.appspot.com',
  );
}
